sbatch inference/scripts/video_effects/beagle_dragon.sh
sbatch inference/scripts/video_effects/bikers_dino.sh
sbatch inference/scripts/video_effects/box_puppy.sh
sbatch inference/scripts/video_effects/coral_jellyfish.sh
sbatch inference/scripts/video_effects/coral_shark.sh
sbatch inference/scripts/video_effects/creek_deer.sh
sbatch inference/scripts/video_effects/cycle_view_explosion.sh
sbatch inference/scripts/video_effects/dancer_audience.sh
sbatch inference/scripts/video_effects/exotic_road_workers.sh
sbatch inference/scripts/video_effects/girl_beach_dog.sh
sbatch inference/scripts/video_effects/girl_living_room_balloons.sh
sbatch inference/scripts/video_effects/girl_living_room_bear.sh
sbatch inference/scripts/video_effects/horse_knight.sh
sbatch inference/scripts/video_effects/jogging_river_golden.sh
sbatch inference/scripts/video_effects/kid_game_bear.sh
sbatch inference/scripts/video_effects/scuba_whale.sh
sbatch inference/scripts/video_effects/taxi_tsunami.sh
sbatch inference/scripts/video_effects/tree_sunlight_elephant.sh
sbatch inference/scripts/video_effects/tree_sunlight_giraffe.sh
sbatch inference/scripts/video_effects/wis_trees_dinosaur.sh